services:
  mtproto-proxy:
    image: telegrammessenger/proxy:latest
    container_name: tg-proxy
    restart: unless-stopped
    expose:
      - "443"
    environment:
      - SECRET=${SECRET:?err}
      - TAG=${TAG:-}
      - WORKERS=${WORKERS:-1}
    volumes:
      - proxy-data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  tls-wrapper:
    image: nginx:alpine
    container_name: tg-tls
    restart: unless-stopped
    ports:
      - "443:443/tcp"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/certs/server.crt:/etc/nginx/certs/server.crt:ro
      - ./config/certs/server.key:/etc/nginx/certs/server.key:ro
    depends_on:
      - mtproto-proxy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  proxy-data:
