services:
  mtproto-proxy:
    image: seriyps/mtproto-proxy:latest
    container_name: tg-proxy
    restart: unless-stopped
    ports:
      - "443:443/tcp"
    command: "-p 443 -s ${SECRET} -t 00000000000000000000000000000000 -a tls"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
