[general]
use_middle_proxy = true

[upstream]
type = "auto"

[server]
port = 443
max_connections = 512
idle_timeout_sec = 120
handshake_timeout_sec = 15
log_level = "info"
rate_limit_per_subnet = 0

[censorship]
tls_domain = "rutube.ru"
mask = true
mask_port = 443
fast_mode = true
drs = true

[access.users]
default = "c763c7a7f6a039e80b2ba84fea81d0d9"

[access.direct_users]
default = true
